### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by qinqon** [qinqon/ovn-kubevirt#1]
- [x] Split ovn deployment into control plane and nodes.
- [ ] Implement "DEL" supporting live migration
  - [ ] Cleanup ovs ports on CNI plugin failure
    - Looks like ovs-cni does not delete them if ovn-kubevirt cni fails
    - This is how ovs-cni does it https://github.com/k8snetworkplumbingwg/ovs-cni/blob/0a5c005cda6e2c6cc02e57953f8959d0af4eab23/pkg/plugin/plugin.go#L433
  - [ ] Clean per VM ip policies
- [x] Do create or update for DHCPOptions instead of just create infinite new ones.
- [x] Assign ip address at VM with ovn virtual DHCP
- [ ] Add chassis to the lsp using `requested-chassis`
- [ ] Test live migration
  - [x] Address follow logical switch port and VM
  - [ ] Connectivity 
  - [ ] Investigate [net.netfilter.nf](http://net.netfilter.nf/)_conntrack_tcp_loose = 1 for snat + live migration
  - [ ] Investigate multi requested-chassis feature for live migration
- [x] Test east/west communication (access to pods on the same namespace). 
- [x] Add north/south communication
  - [x] Fix patch port issue 
  - [x] Add default gw at "public" logical router pointing to kindnet gateway
  - [x] Add dns server using coredns service "kube-dns"  clusterip
    - The host route table is being ignored
- [ ] Services
  - [ ] After dynamic address is present add an annotation to the pod like the ones from multus for the specified network
  - [ ] Change ovn-kubernetes controller to understand `k8s.v1.cni.cncf.io/service-network` so it get the IP from pod's annotation for this network, it wil then create proper endpoints.
- [ ] Isolation/network policies/vlans

learn:
- [ovn + dhcp](https://blog.oddbit.com/post/2019-12-19-ovn-and-dhcp/)
- [Live migration](https://www.youtube.com/watch?v=ijZTMXAg-eI)
- [How to create an Open Virtual Network distributed gateway router](https://developers.redhat.com/blog/2018/11/08/how-to-create-an-open-virtual-network-distributed-gateway-router)
- http://www.openvswitch.org/support/boston2017/1150-ovn-gateways-ipv6.pdf
- [localnet](https://weiti.org/ovn/2018/01/03/ovn-l2-breakout-options.html)
- Load Balancer https://www.cnblogs.com/yaodd/p/7477848.html
- ovn-kuberntes lb:   -  https://github.com/ovn-org/ovn-kubernetes/blob/90d77b70b04530763ed2e8e91bf7a268a25caf42/go-controller/pkg/ovn/loadbalancer/loadbalancer.go#L42
